"""
app/email_sender.py
--------------------
Sends the RCA report as a formatted HTML email via Gmail SMTP.

If email credentials are missing, the function returns "skipped"
without crashing the rest of the RCA pipeline.

Requirements in .env:
  EMAIL_SENDER       = your Gmail address
  EMAIL_APP_PASSWORD = 16-char Gmail App Password (NOT your normal password)
  EMAIL_RECEIVER     = recipient email address

How to get a Gmail App Password:
  1. myaccount.google.com → Security
  2. Make sure 2-Step Verification is ON
  3. Search "App passwords" → Create → name it "RCA Agent"
  4. Copy the 16-character password into .env
"""

import smtplib
import os
import html as html_module
from email.mime.text      import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime             import datetime, timezone


def send_email(report_markdown: str, alert_name: str = "BATRecallDrop") -> str:
    """
    Send RCA report by email.

    Returns:
        "sent"    — email delivered successfully
        "skipped" — credentials not configured
        "failed"  — credentials set but delivery failed
    """
    sender   = os.environ.get("EMAIL_SENDER",       "")
    password = os.environ.get("EMAIL_APP_PASSWORD",  "")
    receiver = os.environ.get("EMAIL_RECEIVER",      "")

    # ── Skip gracefully if credentials not configured ─────────────────────
    if not all([sender, password, receiver]):
        missing = [k for k, v in {
            "EMAIL_SENDER": sender,
            "EMAIL_APP_PASSWORD": password,
            "EMAIL_RECEIVER": receiver,
        }.items() if not v]
        print(f"[Email] Skipped — missing in .env: {', '.join(missing)}")
        return "skipped"

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    subject      = f"AI RCA Report - {alert_name} — {generated_at}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = f"AI RCA Agent <{sender}>"
    msg["To"]      = receiver

    msg.attach(MIMEText(_plain_body(report_markdown, generated_at), "plain"))
    msg.attach(MIMEText(_html_body(report_markdown, alert_name, generated_at), "html"))

    try:
        print(f"[Email] Connecting to smtp.gmail.com:465...")
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender, password)
            server.sendmail(sender, receiver, msg.as_string())
        print(f"[Email] ✓ Report sent to {receiver}")
        return "sent"

    except smtplib.SMTPAuthenticationError:
        print("[Email] ✗ Authentication failed. Use a Gmail App Password, not your normal password.")
        print("[Email]   How to get one: myaccount.google.com → Security → App Passwords")
        return "failed"
    except Exception as e:
        print(f"[Email] ✗ Failed: {e}")
        return "failed"


def _plain_body(report: str, generated_at: str) -> str:
    return (
        "AI-POWERED ROOT CAUSE ANALYSIS REPORT\n"
        "=" * 45 + "\n"
        f"Generated: {generated_at}\n"
        "=" * 45 + "\n\n"
        + report +
        "\n\n" + "=" * 45 + "\n"
        "Auto-generated by AI RCA Agent\n"
        "Powered by Google Gemini 1.5 Flash + LangChain + FAISS\n"
    )


def _html_body(report: str, alert_name: str, generated_at: str) -> str:
    """Convert the Markdown report to clean HTML for the email body."""
    # Simple Markdown → HTML: bold, headers, bullets
    safe = html_module.escape(report)
    # h2 headings
    lines = []
    for line in safe.splitlines():
        stripped = line.strip()
        if stripped.startswith("## "):
            lines.append(f'<h2 style="color:#c0392b;border-bottom:2px solid #c0392b;padding-bottom:4px">{stripped[3:]}</h2>')
        elif stripped.startswith("# "):
            lines.append(f'<h1 style="color:#2c3e50">{stripped[2:]}</h1>')
        elif stripped.startswith("- ") or stripped.startswith("* "):
            lines.append(f'<li>{stripped[2:]}</li>')
        elif stripped.startswith("**") and stripped.endswith("**"):
            lines.append(f'<strong>{stripped[2:-2]}</strong><br>')
        elif stripped == "":
            lines.append("<br>")
        else:
            lines.append(f'{line}<br>')
    body_html = "\n".join(lines)

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="font-family:Arial,sans-serif;max-width:800px;margin:0 auto;padding:20px;background:#f5f5f5">
  <div style="background:#c0392b;color:white;padding:20px;border-radius:8px 8px 0 0">
    <h1 style="margin:0;font-size:20px">🚨 AI Root Cause Analysis Report</h1>
    <p style="margin:6px 0 0;opacity:.85;font-size:13px">
      Alert: {html_module.escape(alert_name)} &nbsp;·&nbsp; Generated: {html_module.escape(generated_at)}
    </p>
  </div>
  <div style="background:white;border:1px solid #ddd;border-top:none;padding:24px;border-radius:0 0 8px 8px">
    {body_html}
  </div>
  <p style="text-align:center;color:#aaa;font-size:11px;margin-top:12px">
    Auto-generated · AI RCA Agent · Gemini 1.5 Flash + LangChain + FAISS
  </p>
</body>
</html>"""
